---
github:
  delete_branch_on_merge: true

release_branches:
  - main

pipelines:
  - verify:
      description: Pull Request validation tests
      public: true

slack:
  notify_channel:
    - docs-notify

subscriptions:
  - workload: habitat-sh/habitat:main_completed:project_promoted:habitat-sh/habitat:main:current:*
    actions:
      - bash:.expeditor/update_generated_content_project_promoted.sh
